; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35216.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?A@@3HA						; A
PUBLIC	?B@@3HA						; B
_BSS	SEGMENT
?A@@3HA	DD	01H DUP (?)				; A
?B@@3HA	DD	01H DUP (?)				; B
_BSS	ENDS
PUBLIC	?foo@@YAXXZ					; foo
PUBLIC	main
; Function compile flags: /Ogtpy
;	COMDAT main
_TEXT	SEGMENT
main	PROC						; COMDAT
; File C:\Users\20131\Desktop\Workplace\CppConsistency\src\compiler_reorder.cpp
; Line 12
	mov	eax, DWORD PTR ?B@@3HA			; B
	inc	eax
; Line 13
	mov	DWORD PTR ?B@@3HA, 1			; B
	mov	DWORD PTR ?A@@3HA, eax			; A
; Line 19
	xor	eax, eax
; Line 20
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?foo@@YAXXZ
_TEXT	SEGMENT
?foo@@YAXXZ PROC					; foo, COMDAT
; File C:\Users\20131\Desktop\Workplace\CppConsistency\src\compiler_reorder.cpp
; Line 12
	mov	eax, DWORD PTR ?B@@3HA			; B
	inc	eax
; Line 13
	mov	DWORD PTR ?B@@3HA, 1			; B
	mov	DWORD PTR ?A@@3HA, eax			; A
; Line 14
	ret	0
?foo@@YAXXZ ENDP					; foo
_TEXT	ENDS
END
