; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35216.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?flag@@3HA					; flag
_BSS	SEGMENT
?flag@@3HA DD	01H DUP (?)				; flag
_BSS	ENDS
PUBLIC	?redundant_store@@YAXXZ				; redundant_store
PUBLIC	?dead_code@@YAXXZ				; dead_code
PUBLIC	main
; Function compile flags: /Ogtpy
;	COMDAT main
_TEXT	SEGMENT
main	PROC						; COMDAT
; File C:\Users\20131\Desktop\Workplace\CppConsistency\src\compiler_remove.cpp
; Line 46
	mov	DWORD PTR ?flag@@3HA, 2			; flag
; Line 48
	xor	eax, eax
; Line 49
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?dead_code@@YAXXZ
_TEXT	SEGMENT
?dead_code@@YAXXZ PROC					; dead_code, COMDAT
; File C:\Users\20131\Desktop\Workplace\CppConsistency\src\compiler_remove.cpp
; Line 33
	ret	0
?dead_code@@YAXXZ ENDP					; dead_code
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?redundant_store@@YAXXZ
_TEXT	SEGMENT
?redundant_store@@YAXXZ PROC				; redundant_store, COMDAT
; File C:\Users\20131\Desktop\Workplace\CppConsistency\src\compiler_remove.cpp
; Line 15
	mov	DWORD PTR ?flag@@3HA, 2			; flag
; Line 16
	ret	0
?redundant_store@@YAXXZ ENDP				; redundant_store
_TEXT	ENDS
END
